### ISSUE TITLE
Multiple Definitions

### ISSUE THREAD

**Issue by keenanlang** [BCDA-APS/Yokogawa_MW100#3]
datum_empty, datum_int, datum_float, and queue_list are defined at global scope in both drvGM10.c and in drvMW100.c causing compilation failures for linux-arm and vxworks. This is currently masked because the module's CONFIG_SITE sets CROSS_COMPILER_TARGET_ARCHS to nothing, meaning only linux-x86_64 is ever built and that compiler doesn't seem to care about the multiple definitions.

**Comment by dohnarms** [comment]
I added "static" to those functions, so this problem should hopefully be fixed now.

**Comment by keenanlang** [comment]
"queue_list" still has conflicts.

**Comment by dohnarms** [comment]
The global functions problem I get.  The queue_list one I don't, as C does allow for identical globals as long as they aren't exported, which they aren't.

Anyway, I renamed them to have no conflicts.

**Comment by keenanlang** [comment]
Here's the relevant part of the compilation, if it helps:

> 
> /APSshare/vw/vxWorks-6.9.4/gnu/4.3.3-vxworks-6.9.4/x86-linux2/bin/ccppc             -DCPU=PPC32  -DvxWorks=vxWorks -include /APSshare/vw/vxWorks-6.9.4/vxworks-6.9.4/target/h/vxWorks.h    -O2   -Wall      -mstrict-align -mlongcall    -fno-builtin  -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/vxWorks -I../../../include -I/APSshare/epics/base-3.15.6/include/compiler/gcc -I/APSshare/epics/base-3.15.6/include/os/vxWorks -I/APSshare/epics/base-3.15.6/include       -I/APSshare/vw/vxWorks-6.9.4/vxworks-6.9.4/target/h -I/APSshare/vw/vxWorks-6.9.4/vxworks-6.9.4/target/h/wrn/coreip -c yokogawaDasExample_registerRecordDeviceDriver.cpp
> /APSshare/vw/vxWorks-6.9.4/gnu/4.3.3-vxworks-6.9.4/x86-linux2/bin/ldppc -r -o yokogawaDasExample  -L../../../lib/vxWorks-ppc32/ -L/APSshare/epics/base-3.15.6/lib/vxWorks-ppc32/                      yokogawaDasExample_registerRecordDeviceDriver.o    -lmw100 -lgm10 -ldbRecStd -ldbCore -lca -lCom
> ../../../lib/vxWorks-ppc32//libgm10.a(drvGM10.o):(.bss+0x0): multiple definition of `queue_list'
> ../../../lib/vxWorks-ppc32//libmw100.a(drvMW100.o):(.bss+0x0): first defined here
> make[3]: *** [yokogawaDasExample] Error 1

**Comment by dohnarms** [comment]
Ok, I see from Tim's VME code you do need to make the variables static as well.

I changed them, so it should all work now.
